### ISSUE TITLE
History file remains open if promptLoop terminates without executing exit command

### ISSUE THREAD

**Issue by hoomanv** [spring-projects/spring-shell#113]
spring-shell version: 1.2.0-RELEASE

In JLineShell class, promptLoop method blocks on invocation of reader.readLine().
If readLine() returns null, the loop will be terminated and it forgets to close the fileLog.
This happens quite easily for example by pressing CTRL+D on a ssh terminal.
fileLog is currently only closed after calling logCommandToOutput method, which was a very optimistic decision in the first place.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
