### ISSUE TITLE
Implement custom parser that supports triple quotes

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#139]
_From @ericbottard on January 13, 2016 14:40_

_Copied from original issue: ericbottard/spring-shell2#16_

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
