### ISSUE TITLE
Implement infinite arity

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#140]
_From @ericbottard on January 7, 2016 11:56_

_Copied from original issue: ericbottard/spring-shell2#11_

**Comment by ericbottard** [comment]
Blocks https://github.com/spring-cloud/spring-cloud-skipper/issues/316

**Comment by Coada** [comment]
+1 for this feature. I need it to properly map it to varargs.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
