### ISSUE TITLE
can't use in an offline environment

### ISSUE THREAD

**Issue by immadolf** [spring-projects/spring-shell#206]
Hi,i generate a project from [http://start.spring.io/](http://start.spring.io/),and it works in an online environment.Then ,i copied the whole local maven repository and the project to an offline environment.When i open the project in IDEA , it shows a red line in `pom.xml` and tips "Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.RELEASE in xxx(the mirror name of my company's nexus )".But my local repository had all needs dependencies and the "org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.RELEASE" seems to be incorrectly formatting，in my mind the correct format is `groupId:artifactId:version:package`.
Sorry for my poor English , could you tell me what happened in there?

**Comment by ericbottard** [comment]
This doesn't seem to be a problem with the coordinates of the reference in the pom, if it worked on a different environment.
If indeed everything is setup correctly in the second environment, then wiping your complete maven repository and trying to build the project should work (going through your company nexus). If not, then I believe the problem lies in the configuration of that proxy.

Could you post the contents of the generated project (or at the very least the pom file)?

**Comment by immadolf** [comment]
Thank you for your reply.
Here is my project.
[demo.zip](https://github.com/spring-projects/spring-shell/files/1802608/demo.zip)
And it works in an online PC.
![default](https://user-images.githubusercontent.com/12369197/37282702-520003ba-2630-11e8-9972-f11bfdc2c562.png)
Then i copy my repository to the offline PC.
online
![default](https://user-images.githubusercontent.com/12369197/37282905-f9bde284-2630-11e8-82a1-e3733c52614e.png)

offline
![default](https://user-images.githubusercontent.com/12369197/37282884-eac5c65c-2630-11e8-8792-123c7a0bcead.png)

Run `mvn clean`.
![default](https://user-images.githubusercontent.com/12369197/37282985-4a4c80f2-2631-11e8-859c-9235bc563cd2.png)

![default](https://user-images.githubusercontent.com/12369197/37283169-f425b558-2631-11e8-99c8-df399978fcf1.png)

**Comment by immadolf** [comment]
I got it.
I use maven mirror to download jars , these jars doesn't works by copy.
Now,i download from central and it works.
thks.
