### ISSUE TITLE
Suppress command output in help command?

### ISSUE THREAD

**Issue by jasonwjones** [spring-projects/spring-shell#207]
In one of my programs using Spring Shell, it would be nice to have "hidden" commands, such that when the user entered `help` the command would not show. This could be controlled with an optional boolean setting in `@ShellMethod` named `hidden` or something that by default is false. Tab completion would still work for these commands, however.

**Comment by ericbottard** [comment]
This issue already came up in Shell 1 and I'm rather not in favor of it.
If you have a command, then it is there and can be invoked anyway. You'd better document it anyway, so that your users don't mess things up.

If really what you want is noob vs expert commands, or you feel like you're overwhelmed by the number of commands, I suggest you use the grouping function that's new in Shell 2

**Comment by jasonwjones** [comment]
Fair enough. At present I am grouping into an 'Advanced' commands type of category. I was partially inspired for this type of attribute because JCommander offers such functionality (I think via a visible = boolean annotation). I see where you are coming from, though.
