### ISSUE TITLE
Support for Optional<> parameters

### ISSUE THREAD

**Issue by jasonwjones** [spring-projects/spring-shell#212]
I have several commands where a parameter is optional (in the sense that it has a `defaultValue = ShellOption.NULL` annotation) but there isn't a default value that makes sense to assign statically. Based on how the code works in several of these methods, the way I can treat these is by wrapping them in `Optional` or adding logic to assign them an appropriate default value at runtime.

It seems that it might be possible to just implement a `Converter<String, Optional<Foo>>` but given that `Optional` is a foundational type (and Spring Shell relies on Java 1.8+), I think it would be nice to support `Optional` "out of the box" for method parameter injection, in conjunction with the current support for Converter.

For example, I may have this method:

```
public void comments(@ShellOption Foo foo) { ... }
```

And already have a corresponding converter:

```
@Component
public class FooConverter implements Converter<String, Foo> { ... }
```

Given this it'd be nice if this worked, with no additional converters needed:

```
public void comments(@ShellOption Optional<Foo> foo) { ... }
```

Thoughts?

**Comment by c4deszes** [comment]
Made a pull request #287 

I support this feature and actually the current resolver will fill `Optional<T>` but if the parameter doesn't exist it will fail. The solution is to specify `@ShellOption.optOut` and have a custom ParameterResolver that supports Optional and resolves everything into `Optional.empty()`. But same story as with `defaultValue` because you would have to specify optOut for every Optional argument.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
