### ISSUE TITLE
Is there anyway to turn off/configure INFO logging?

### ISSUE THREAD

**Issue by kasiprasad** [spring-projects/spring-shell#218]
2018-05-10 12:07:55.020  INFO [pid] --- [           main] c.p.[CLASS]

I was hoping to turn off this type of logging for my PROD builds.

Please let me know if this is possible.

Thanks.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
