### ISSUE TITLE
How can I test my spring-shell app?

### ISSUE THREAD

**Issue by carloslimasis** [spring-projects/spring-shell#223]
Hi there!

I needed to develop a shell application and my choice for this was the Spring-Shell. I have some doubts about how can I test my spring shell application.

I saw a discussion about tests with spring shell in the following link, but It was not very clear to me.

https://github.com/spring-projects/spring-shell/issues/171

**Comment by jarlah** [comment]
Testing is by far the least things i am worried about. Since Shell components are spring beans i can make a unit test with spring with h2 database and setup and teardown before and after each test. H2 has a drop all objects sql. 

Then you can just test the Shell methods. Of course you cannot test that you can type in Shell commands and verify that they work in terminal. But you shouldnt test spring shell or jline. So test Shell components is my advice.

**Comment by rmcdouga** [comment]
> But you shouldnt test spring shell or jline. So test Shell components is my advice.

I don't agree with this.  You still need to perform integration tests (is my command being picked up? does it run properly within the Spring environment?)

You can do this manually, but its far more efficient to do it with automation.  Issue #204 provides advice on how to do this.

**Comment by jvalkeal** [comment]
Closing if favour of #489 and tracking related work there.
