### ISSUE TITLE
Improvement - Provide easy way to pass raw (not parsed) command line to method parameter

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-shell#224]
For my project I need to get a line content, not parsed parameters into the command parameter, but I don't see any easy way how to do it. Parameter resolver already gets parsed list of values.  It would be fine to get access to Input from Shell.evaluate.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
