### ISSUE TITLE
Tab Completion doesn't work in Intellij

### ISSUE THREAD

**Issue by mtj8033** [spring-projects/spring-shell#227]
Tab Completion doesn't work in Intellij, is there anyway to make it work?

**Comment by niklasastrom** [comment]
@mtj8033 I recently figured out the same, did you get it to work?

**Comment by dbrimley** [comment]
+1 to get this fixed

**Comment by justin-wesley** [comment]
Without looking into anything, isn't this something that would fall on JetBrains, and not Spring Shell? When launching a Spring Shell app in Intellij, the terminal is not available. You may notice the output:
 
`org.jline                                : Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`

This to me seems like an issue on Intellij's side since the output from the Debug or Run execution isn't in an actual terminal.

**Comment by justin-wesley** [comment]
@mtj8033 Just curious, does this work in Eclipse or Spring Tool Suite?

**Comment by justin-wesley** [comment]
> @mtj8033 Just curious, does this work in Eclipse or Spring Tool Suite?

Just checked and Eclipse has the same issue.

**Comment by res1st** [comment]
it only works if I start my application with java -jar, not in Eclipse.
I also didn't find a way to make it work. :-(

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.

**Comment by jschavey** [comment]
Can confirm this remains an issue with Spring Shell v2.1.1 and IntelliJ 2022.

**Comment by zthreefires** [comment]
> Does not work in Spring Shell 3.0.1 and IntelliJ 2023.1.3
> I get `org.jline : Unable to create a system terminal, creating a dumb terminal`

Hi , have you solved the problem?

**Comment by dkamenov** [comment]
I just ran into this issue while running in a Docker container via  `docker exec -it my-container bash` and then running the spring-shell (2.1.12) application. After enabling DEBUG, I get
```
        Caused by: java.io.IOException: Error executing 'tty': not a tty
                at org.jline.utils.ExecHelper.exec(ExecHelper.java:41)
                at org.jline.terminal.impl.ExecPty.current(ExecPty.java:42)
                ... 124 common frames omitted

2023-10-13 17:37:55.464 DEBUG 2260 --- [           main] org.jline                                : Using terminal DumbTerminal
```

Bash autocompletion works just fine in this shell.
```
[myuser@72601bb05878 ~]$ echo $TERM
xterm
```
