### ISSUE TITLE
`@ConditionalOnProperty` target property with no metadata

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-shell#231]
Several auto-configurations use a condition on a property that has no metadata. As a result, trying to use it to customize the auto-configuration lead to a warning in an IDE.

The report detected the following:

```
org.springframework.shell.jline.JLineShellAutoConfiguration#interactiveApplicationRunner [spring.shell.interactive.enabled]
org.springframework.shell.jline.JLineShellAutoConfiguration#scriptApplicationRunner [spring.shell.script.spring.shell.script]
org.springframework.shell.standard.commands.StandardCommandsAutoConfiguration#clear [spring.shell.command.clear.enabled]
org.springframework.shell.standard.commands.StandardCommandsAutoConfiguration#help [spring.shell.command.help.enabled]
org.springframework.shell.standard.commands.StandardCommandsAutoConfiguration#quit [spring.shell.command.quit.enabled]
org.springframework.shell.standard.commands.StandardCommandsAutoConfiguration#script [spring.shell.command.script.enabled]
org.springframework.shell.standard.commands.StandardCommandsAutoConfiguration#stacktrace [spring.shell.command.stacktrace.enabled]
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.

**Comment by snicoll** [comment]
A quick check shows that the above have metadata now.
