### ISSUE TITLE
How could I integrate Spring-shell with text-io or Swing ?

### ISSUE THREAD

**Issue by richardthibault** [spring-projects/spring-shell#232]
Hello,

I'm currently using Text-Io (org.beryx.textio) in a Swing Application to execute a shell widget, and I would like to replace my in-house shell management parser and executor with Spring-shell, which is more powerfull and extendable, but I would like to keep Text-Io to manage the shell display (input and output of shell lines).
Because all the integrations capabilities are a bit confusing for me, would you have a sample app that integrates spring-shell with text-io or that integrates spring-shell with a Swing TextArea as InputProvider and Output displayer ?

Thank you in advance !
Regards,

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
