### ISSUE TITLE
Is it Possible to run Spring-Shell with JDK 7

### ISSUE THREAD

**Issue by LutherTsaiTW** [spring-projects/spring-shell#233]
I'm now working on spring-boot project with Spring-Shell as a command line tool.
It all works well at local development environment.
However, the online-environment which I use right now is running with JDK 7, and unfortunately it could not be upgraded to JDK 8 or newer. 

I would like to ask if it is possible to use spring-shell with JDK 7!
This is the dependency what I use below...

```
<dependency>
	<groupId>org.springframework.shell</groupId>
	<artifactId>spring-shell-starter</artifactId>
	<version>2.0.0.RELEASE</version>
</dependency>
```

**Comment by ericbottard** [comment]
Hi Luther,

I'm afraid this is not possible, as Spring Shell 2 uses extensive JDK8+ features such as streams on collections, etc

There may be some hacky way to retrofit streams in JDK7, but I don't know much about that and sadly can't help you with that. Your best bet may be to really try to use JDK8+ (if only because JDK7 has reached end of life)

Sorry
