### ISSUE TITLE
Need to call operating system commands in the spring shell

### ISSUE THREAD

**Issue by zengqingjun** [spring-projects/spring-shell#235]
Need to call operating system commands in the spring shell。
How to use？

**Comment by ericbottard** [comment]
Until infinite arity for parameters, this is gonna be a little awkward but:

Create a Spring Shell command that does that (you may want to call it `!` for example). Such a command would read the rest of its arguments (either you hardcode the number of args because you know which system commands you want to support, or use just one arg which you'll split yourself on spaces -- the use will have to surround it with quotes) and turn that into the command to execute (using JDK's `Process` class).

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
