### ISSUE TITLE
Project page displays latest release as SNAPSHOT

### ISSUE THREAD

**Issue by justin-wesley** [spring-projects/spring-shell#245]
Currently, the project page has 2.0.1 as the SNAPSHOT release and that version has been released since April.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
