### ISSUE TITLE
How to get user input inside @shellmethod

### ISSUE THREAD

**Issue by cqpine** [spring-projects/spring-shell#254]
Hello, my work(windows) need to get user input inside the @shellmethod ； but i find i can't get the user's input , the result isn't completely , eg: user input 123 , the result will be 2 ;but it work well at linux . please help me...thanks

@ShellComponent
public class Test {
	@ShellMethod(value = "测试")
	public void test1() {
		System.out.println("hello");
		BufferedReader inreader = new BufferedReader(new InputStreamReader(System.in));;
		String keystr = null;
        try {
			keystr = inreader.readLine();
			System.out.println(keystr);
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
}

**Comment by dinhtienloc** [comment]
Spring Shell is built on top of JLine, it uses org.jline.reader.LineReader as a Singleton Bean.
`@ShellComponent` is still a kind of Spring `@Component`. So you can inject org.jline.reader.LineReader in your class and use it to read user input while executing the command.

```java
@ShellComponent
public class Test {
  @Autowired
  @Lazy
  private LineReader lineReader;

  @ShellMethod(value = "测试")
  public void test1() {
    System.out.println("hello");
    String value = this.lineReader.readLine("Input something here:");
    System.out.println("User input: " + value);
  }
}
```
 Need to use `@Lazy` because SpringShell loads the commands to context before initializing LineReader.

**Comment by cqpine** [comment]
> Spring Shell is built on top of JLine, it uses `org.jline.reader.LineReader` as a Singleton Bean.
> `@ShellComponent` is still a kind of Spring `@Component`. So you can inject org.jline.reader.LineReader in your class and use it to read user input while executing the command.
> 
> ```java
> @ShellComponent
> public class Test {
>   @Autowired
>   @Lazy
>   private LineReader lineReader;
> 
>   @ShellMethod(value = "测试")
>   public void test1() {
>     System.out.println("hello");
>     String value = this.lineReader.readLine("Input something here:");
>     System.out.println("User input: " + value);
>   }
> }
> ```
> 
> Need to use `@Lazy` because SpringShell loads the commands to context before initializing LineReader.

OK，thanks for your answer，I will try it immediately

**Comment by yarix** [comment]
this can be closed since the above example simply works.
it's worth mention that since Jline is used, its also very easy to mask inputs, for example passwords.
`String value = this.lineReader.readLine( "enter your password: ", '*');`

**Comment by BOFA1ex** [comment]
it better to upgrade jline version.
spring-shell-parent just supported jline 3.4.0.
i try to upgrade the version mandatorly to latest(3.14.1).
the readline give more api such as printAbove.

#Example 
```java
lineReader.printAbove(AttributedStringBuilder
    .append("hello", "welcome", "spring-shell", "jline-console")
    .styleMatches(Pattern.compile(".*"), AttributedStyle.DEFAULT.foreground(AttributedStyle.RED))
);
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
