### ISSUE TITLE
Dose spring shell support process execution?

### ISSUE THREAD

**Issue by MingningShao** [spring-projects/spring-shell#271]
Hi,
How can I Use the spring shell(v2.0) as an interaction tool, like an process executor.
Execute a command step by step with a friendly tips for customer.
Then, the user could have a good experience.
Currently, it seems that the spring shell can only execute one command then back to the main menu, not a process execution.
Thanks!

**Comment by MroZ11** [comment]
It's the same as I thought, but this library may not be maintained

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
