### ISSUE TITLE
Is it possible to recognize backslash characters in a command ?

### ISSUE THREAD

**Issue by jeffersonlsz** [spring-projects/spring-shell#280]
Hi there,

I need to implement a command like "**loadfile** C:\path1\path2\A1.txt" . The problem is that when I type the backslashes, the prompt seems just to ignore it and it becomes C:path1path2A1.txt. Even eclipse debbugin doesn't help much on finding why it happens.

Any tip on how to do that ? Is that even possible ?

**Comment by rajjaiswalsaumya** [comment]
This is expected. Windows \ is removed during path read as that is considered as escape character. You need to either put two backslash or always use forward slash as windows basics comes from mother Unix, it works straight a way if you just use single forward slash

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.

**Comment by DineshSolanki** [comment]
Even though it works with Unix line path syntex, it would be good addition to feature, if we had some kind of option to mimic same behaviour with windows like path as most user would directly copy from windows explorer which default to backslashes.
