### ISSUE TITLE
Issue in Exit/Quit Command

### ISSUE THREAD

**Issue by akhileshtripa** [spring-projects/spring-shell#284]
I have written custom shell for my client application. My all commands are working fine except "Quit/Exit" command. When I Override Quit Command interface and write System.exit(0) inside my custom logic, entire sprint boot application goes down. please suggest?

**Comment by c4deszes** [comment]
By default the Quit command simply does:
https://github.com/spring-projects/spring-shell/blob/296db93462eac8a9d6b10009a2e3f7b9fe22f5ad/spring-shell-standard-commands/src/main/java/org/springframework/shell/standard/commands/Quit.java#L46

Which is then catched in the REPL cycle of the Shell.
https://github.com/spring-projects/spring-shell/blob/296db93462eac8a9d6b10009a2e3f7b9fe22f5ad/spring-shell-core/src/main/java/org/springframework/shell/Shell.java#L124-L147

So calling quit/exit by default doesn't kill the application, it just stops the shell from the taking inputs from the command line interface. Note that `run(InputProvider inputProvider)` calls 'evaluate(Input input)' so if you have autowired the Shell into your application you can still call commands in your code.

If the only dependency you have is Spring Shell then your application should stop on an ExitRequest because it's the only Thread that was running. Once you have web or any other running thread then it's going to keep the application alive.

`System.exit(0)` tries to shutdown the JVM (all threads), if you don't want to close the application on the 'exit' command then don't override it. If you want it to close but gracefully then you could use `SpringApplication.exit` or `ApplicationContext::close` these will call `close()` on `DisposableBean`-s and `@PreDestroy` methods.

**Comment by BOFA1ex** [comment]
> the error(ExitRequest&EndOffFileException) will be catch by org.springframework.shell.result.ThrowableResultHandler.
need to catch explicitly and break the loop.
```java
Input input;
try {
    input = inputProvider.readInput();
    /*
    * change here
    * - add: keymap ctrl+c/d
    */
} catch (ExitRequest | EndOfFileException e) {
      break;
} catch (Exception e) {
      resultHandler.handleResult(e);
      continue;
}
if (input == null) {
      break;
}
result = evaluate(input);
if (result != NO_INPUT && !(result instanceof ExitRequest)) {
      resultHandler.handleResult(result);
}
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
