### ISSUE TITLE
The error of spring-shell home page.

### ISSUE THREAD

**Issue by zhuzhuman978** [spring-projects/spring-shell#295]
There is an error in the quick start part of this project's [home page](https://projects.spring.io/spring-shell/).
```    @ShellMethod("Translate text from one language to another.")
    public String translate(
      @ShellOption(mandatory = true) String text,
      @ShellOption(mandatory = true, defaultValue = "en_US") Locale from,
      @ShellOption(mandatory = true) Locate to
    ) {
      // invoke service
      return service.translate(text, from, to);
    }
```
The preceding code `@ShellOption(mandatory = true) Locate to` is wrong.
![error of spring-shell home page quick-start](https://user-images.githubusercontent.com/53943926/71583921-5b264e00-2b4b-11ea-9a2b-096e249510be.png)

@ericbottard @royclarkson @rmorgan @jvalkeal @joshlong @scottfrederick

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
