### ISSUE TITLE
Abandoned? Needs contributors?

### ISSUE THREAD

**Issue by csueiras** [spring-projects/spring-shell#302]
Hi

I recently started making use of this project for some internal tooling at my company. While looking at the state of this repository and documentation it appears that this project is in some state of abandonment, given that there hasn't been any merges since October 2019, and some documentation hasn't been updated since 2018.

Questions: is this project abandoned? Perhaps is this project looking for contributors? Or is this project being replaced by some other? I would be happy to contribute to this project, but its not particularly clear to me who is running this project and how to get started contributing (I see various unmerged PRs).

Can someone clarify the state of the world and how can the community help to push this project forward, please?

Thanks

-Christian

**Comment by c4deszes** [comment]
It's not a top priority project for the Spring team, that's the main reason it's not actively maintained. The reason why it's not high priority is because it's not directly related to their market, which is web development, The use cases for their customers are minimal. Personally I don't see this project being worked on anymore. It's been pulled from the Spring Initializr, it's based on an old CLI library so it could eventually run into roadblocks.

If you're looking for an alternative that's maintained then try [PicoCLI](https://github.com/remkop/picocli) . If you need some web specific functionality then I have a fork [Spring Shell WebSocket](https://github.com/c4deszes/spring-shell) that has a websocket adapter implemented with stuff like login through Spring Security.

**Comment by csueiras** [comment]
Thanks @c4deszes I've now taken a closer look at PicoCLi, and its integration with Spring Boot. That integration doesn't seem even close as well integrated into Spring as this one. I'll consider forking this myself, thanks again. I'll close this issue.

**Comment by Jarjanazy** [comment]
Hopefully it is :D I plan to contribute to it
