### ISSUE TITLE
Non intuitive ScriptShellApplicationRunner condition values

### ISSUE THREAD

**Issue by imbirevkotlya** [spring-projects/spring-shell#307]
It seems like, ScriptShellApplicationRunner have copy-paste issue with condition names:

       public static final String SPRING_SHELL_SCRIPT = "spring.shell.script";
	public static final String ENABLED = "spring.shell.script";

	/**
	 * The name of the environment property that allows to disable the behavior of this
	 * runner.
	 */
	public static final String SPRING_SHELL_SCRIPT_ENABLED = SPRING_SHELL_SCRIPT + "." + ENABLED;

Which is provide to user write some code like this in the configuration:
`spring.shell.script.spring.shell.script=true`

Seemingly, the variable ENABLED should be revalued to 'enabled', but maybe I'm wrong..

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
