### ISSUE TITLE
java.lang.IllegalStateException: Failed to execute ApplicationRunner

### ISSUE THREAD

**Issue by orange-guo** [spring-projects/spring-shell#311]
It failed after starting my environment via gradle bootRun. 
The indirect error comes from the logic implementation (readInput) on line 129 of org.springframework.shell.Shell. 
The internally encapsulated ParsedLine may be empty (I think the internal implementation logic may be due to the incompatibility between the internal Jline library and the terminal, usually this logic will block the console and wait for the user to input the value )
It only checked whether the returned result was null, but did not detect the ParsedLine object that it wrapped. After this detailed check was omitted, the subsequent logic implementation threw a confusing error.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
