### ISSUE TITLE
Boolean parameter overrides first optional String parameter

### ISSUE THREAD

**Issue by netp-dany** [spring-projects/spring-shell#319]
Hi, I was working on a project that uses spring shell and I did notice unexpected outcome when using Boolean parameters in 
@ShellMethod. The Boolean value is assigned to first optional String parameters as well as to the Boolean itself.

Example:

`  
  @ShellMethod(value = "TEST")
  public void test(@ShellOption(defaultValue = "") String varString1,
                   @ShellOption(defaultValue = "") String varString2,
                   @ShellOption(defaultValue = "") String varString3,
                   @ShellOption() Boolean varBoolean1) {

    System.out.println("varString1 : " + varString1);
    System.out.println("varString2 : " + varString2);
    System.out.println("varString3 : " + varString3);
    System.out.println("varBoolean1 : " + varBoolean1);
  }
`

now if we type the following shell command

`test --var-boolean1 true`

we will get the following outcome

`
varString1 : true

varString2 : 

varString3 : 

varBoolean1 : true
`

**Comment by ruanwenjun** [comment]
@netp-dany This is strange, but you can execute `test --var-boolean1` to get what you want.
```
varString1 : 
varString2 : 
varString3 : 
varBoolean1 : true
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
