### ISSUE TITLE
add support to spring-native

### ISSUE THREAD

**Issue by ivangfr** [spring-projects/spring-shell#323]
Hi, I have this project [`springboot-rsocket-webflux-aop`](https://github.com/ivangfr/springboot-rsocket-webflux-aop) and one of its applications called `movie-client-shell` uses `spring-shell`.

I've tried to add `spring-native` to the app. However, when building the jar file, I'm getting the following exception
```
...
INFO 11514 --- [           main] o.s.nativex.support.SpringAnalyzer       : Spring Native operating mode: native
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 53 source files to /springboot-rsocket-webflux-aop/movie-client-shell/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /springboot-rsocket-webflux-aop/movie-client-shell/target/generated-test-sources/spring-aot/src/test/java/org/springframework/aot/MovieClientShellApplicationTestsContextInitializer.java:[115,39] cannot find symbol
  symbol:   class JLineShellAutoConfiguration$HistoryConfiguration$$EnhancerBySpringCGLIB$$53a5ca59
  location: package org.springframework.shell.jline
[INFO] 1 error
[INFO] -------------------------------------------------------------
...
```

**How to reproduce**

- git clone https://github.com/ivangfr/springboot-rsocket-webflux-aop.git
- cd springboot-rsocket-webflux-aop
- git checkout include-spring-native
- ./mvnw clean package --projects movie-client-shell -DskipTests

I'm using

- **spring-boot** `2.6.1`
- **spring-native** `0.11.0-RC1`

**Comment by jvalkeal** [comment]
This is definitely on a radar as making shell native would make it work like a proper command as it's been nuance that jvm bootstrap takes that additional second(s). On a `3.x` line we're trying to clean things out and make other spring/boot things more friendly for particular versions so that we'd be more ready for native compilation.

**Comment by jvalkeal** [comment]
Native support for shell in a main branch is starting to show some light. There's been some major refactoring for `3.x` to bring code up-to-date with boot `2.6.x` line and with it more close to `graal` support. Mostly this rework has been to remove bean cycles seen by boot and trying to do less magic things which usually breaks with `graal` unless specific `spring-native` config is in place.

Essentially basic stuff now works expect #340 which may need a proper support module with `spring-native` or with `spring-shell` itself when its possible to use it as a production ready feature. Most likely there are other corner cases where things break depending how graal and spring-native evolve.

When compiling with `./mvnw clean package -Pnative` using `jkd11` you can get something like:
[![asciicast](https://asciinema.org/a/TSHhWFYT3wxA3Kf9VXItNyUGc.svg)](https://asciinema.org/a/TSHhWFYT3wxA3Kf9VXItNyUGc)

**Comment by ivangfr** [comment]
That is great! Thanks @jvalkeal for working on it and for the support!

**Comment by jvalkeal** [comment]
I'm probably going to close this issue soon as complete while there is no official native support yet. This because:

- We partly have graal json configs in place which it can use as is.
- What comes for spring support we can't depend on `spring-native` in shell itself as it is experimental.
- Sample application is however using `spring-native` and shows how one could build native shell app.
- Proper native support can only come with `spring-boot 3.x` which gets native support from framework itself.

**Comment by jvalkeal** [comment]
Marking complete as work for a real native support starts after `2.1.0` is released and main moves to `spring-boot 3.x`.
