### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by spoerri** [spring-projects/spring-shell#413]
Could you accept a PR to add support for a simple web GUI that works in the spirit of the CLI?

Each command could get an HTML form, and each parameter could get a form input field.

So the same application function could be invoked either from the CLI or the web GUI, with perhaps no changes to the application's configuration of spring.

**Comment by jvalkeal** [comment]
I feel this kind of functionality is out of scope of spring-shell itself. But to understand your idea better can you describe what problem you're trying to resolve?

I'm asking because there are various projects to provide online "shells" and executing command tooling which spring-shell really is. I have a feeling you'd like to use spring-shell as a wrapper to "execute" something within an context of a running boot app or something similar?

**Comment by spoerri** [comment]
The same configuration (eg java annotation and other speing-shell api) which causes spring-shell to provide a CLI that wraps the user app could also cause spring-webshell to provide a web GUI that wraps the user app. Spring-webshell might not share much code with spring-shell. It would be nice to be an alternate implementation of the same interface from the user-app point of view, and enable the actual user to do all the same things she can do with spring-shell, just via a web browser instead of a via terminal session.

Having it be part of spring would give it some nice visibility. With code review, it would ensure that its style and standards are consistent with the rest of the spring project, and assuming you like it, it could also enable the feature to survive even if I can’t maintain it in the future.

**Comment by spoerri** [comment]
Yes, could do, thanks for feedback

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
