### ISSUE TITLE
[Enhancement]  Support component level prefix.

### ISSUE THREAD

**Issue by Koooooo-7** [spring-projects/spring-shell#531]
Normally, we collect the related command under the same `@ShellComponent`,  and we may wanna add a common prefix for each command instead `concat` it in each `@ShellMethod` key.
```java
	@ShellComponent(prefix = "docker-prefix")
	public static class ShellComponentWithPrefix {

		@ShellMethod(value = "run")
		public void foo1(...) {
		}
                 
                 @ShellMethod(value = "build")
		public void foo2(...) {
		}

	}
```
It should be 
```
docker-prefix run
docker-prefix build
```

**Comment by jvalkeal** [comment]
`@ShellComponent' is really just a meta-annotation for `@Component` and to instruct shell to inspect those beans and thus should not get mixed with shell methods. In spring mvc it would be like mixing `@RestController` to have something for `@RequestMapping`.

It might be better to support `@ShellComponent` on a class-level so that defaults for method level annotations could be defined there. For example in spring mvc `@RequestMapping` can be defined on class/method level and if so path value is concatenated. It's a same idea you have here.

**Comment by Koooooo-7** [comment]
> `@ShellComponent` is really just a meta-annotation for `@Component` and to instruct shell to inspect those beans and thus should not get mixed with shell methods. In spring mvc it would be like mixing `@RestController` to have something for `@RequestMapping`.
> 
> It might be better to support `@ShellComponent` on a class-level so that defaults for method level annotations could be defined there. For example in spring mvc `@RequestMapping` can be defined on class/method level and if so path value is concatenated. It's a same idea you have here.

I see, it seems here should have a separated  annotation such as `@ShellPrefix` to do the thing and can be concat on class level as well.

**Comment by Koooooo-7** [comment]
> `@ShellComponent` is really just a meta-annotation for `@Component` and to instruct shell to inspect those beans and thus should not get mixed with shell methods. In spring mvc it would be like mixing `@RestController` to have something for `@RequestMapping`.
> 
> It might be better to support `@ShellComponent` on a class-level so that defaults for method level annotations could be defined there. For example in spring mvc `@RequestMapping` can be defined on class/method level and if so path value is concatenated. It's a same idea you have here.


I see, but it seems it is kinda different to the relationship between `@RestController` and `@RequestMapping`. because those commands have `Group`,  IMO the `Group` is more like cross class `@RequestMapping` and the  `@ShellComponent` is the class level `@RequestMapping`, and the `@ShellMethod` key is the method level `@RequestMapping`.  
The whole picture about the prefix I assumed we could collect/manage commands/subcommans like this.
```
Common Group Name
   // group level prefix         // class level prefix      // method level prefix
      command                       redis                             slot
      command                       spring                           start
```

**Comment by jvalkeal** [comment]
Now that you mentioned adding new annotations, it's actually something what has been on my mind but never created an issue for it. Now that all commands are based on `CommandRegistration` and those can also be registered as a simple beans it would make sense to have new annotation model with better designed annotations.

`@ShellMethod` is the original and was made to work with older model where all command methods were resolved by using reflection. That annotation doesn't really map that well with `CommandRegistration`. It might be good thing to deprecate `@ShellComponent` and `@ShellMethod` in favour of annotations which are designed to work better what we have now with command registration system. There is a lot of new functionality in `CommandRegistration` which cannot be used with `@ShellMethod`.

Starting from scratch to design a new annotation model would take us to better modern model of defining shell commands. Like having a group annotations would make sense for example.

**Comment by Koooooo-7** [comment]
> Now that you mentioned adding new annotations, it's actually something what has been on my mind but never created an issue for it. Now that all commands are based on `CommandRegistration` and those can also be registered as a simple beans it would make sense to have new annotation model with better designed annotations.
> 
> `@ShellMethod` is the original and was made to work with older model where all command methods were resolved by using reflection. That annotation doesn't really map that well with `CommandRegistration`. It might be good thing to deprecate `@ShellComponent` and `@ShellMethod` in favour of annotations which are designed to work better what we have now with command registration system. There is a lot of new functionality in `CommandRegistration` which cannot be used with `@ShellMethod`.
> 
> Starting from scratch to design a new annotation model would take us to better modern model of defining shell commands. Like having a group annotations would make sense for example.

Yes, I do agree that the `@ShellMethod` is not that much as flexible as `CommandRegistration` in current implementations. and it is hard to handle those functions align to `CommandRegistration` for now. 

I m glad to know the new  command registration system roadmap. But If the new system, which would break the backward compatibilities for previous `2.x` versions. doesn't it matter ? 
Instead, If we decide to support both the new system and the `original implementations`( @ShellConponent @ShellMethod, even @ShellOptions) ,  I think it would be more complicated, because they are in different design way.

**Comment by lppedd** [comment]
> If we decide to support both the new system and the original implementations

If there is a plan to restructure the annotations - for release 3.0 - then I'd like the breaking changes more.
There is really no need to support old stuff when the new one is better, it only adds weight and maintenance cost.

**Comment by jvalkeal** [comment]
In a spring world we try to make transition between versions easy for users. Change of major version is usually for bigger infrastructure changes like in `3.x` we baseline jdk 17 together with boot 3.x and framework 6.x. We can break things between minor versions as well, it's just balancing act how frustrated we make users for upgrades. That's why, if possible, deprecation comes first so that it gives users a time to move away before things completely break.

Being honest a possible new annotation system would not be a breaking change, just new better designed model. If that gives enough carrot for a users then they are more inclined to upgrade before deprecated part is taken away.

**Comment by jvalkeal** [comment]
Just to clarify some things, there is no new command registration roadmap as that's already in place in both `2.1.x` and `3.x`.

Changes between `2.0.x` and `2.1.x` was initiated from a simple issue #324. Initially we just wanted to address bean cycles but it became clear it was not possible without a bigger internal rewrite mostly due to fact that old code base dated back to spring boot 1.x time(spring-shell did exist before boot).

We chose to make bigger rewrite in `2.1.x`, trying to keep api's same, instead of postponing further changes until `3.x`.

**Comment by Koooooo-7** [comment]
> Just to clarify some things, there is no new command registration roadmap as that's already in place in both `2.1.x` and `3.x`.
> 
> Changes between `2.0.x` and `2.1.x` was initiated from a simple issue #324. Initially we just wanted to address bean cycles but it became clear it was not possible without a bigger internal rewrite mostly due to fact that old code base dated back to spring boot 1.x time(spring-shell did exist before boot).
> 
> We chose to make bigger rewrite in `2.1.x`, trying to keep api's same, instead of postponing further changes until `3.x`.

Gotcha, I thought there I could have something to do about the command registration annotation system stuff/enhancement to do. now it seems nothing left here to do until the `3.x` comes.
About the `prefix` enhancement propose， I guess it is unnecessary for now.
